-- Baseline migration: mirrors the schema Hibernate already created in the
-- live database via spring.jpa.hibernate.ddl-auto=update (that was the
-- only source of schema truth before Flyway was introduced).
--
-- IMPORTANT: this file is NOT executed against the existing production
-- database. spring.flyway.baseline-on-migrate=true + baseline-version=1
-- (see application.properties) tell Flyway to record V1 as already
-- applied on any database that isn't empty, without running it. It only
-- actually runs against a genuinely fresh database (a new local dev DB,
-- a test container, etc.), where it must produce the same schema the
-- entities already expect.
--
-- Before deploying this, double-check these column definitions against
-- the real Supabase schema (e.g. `\d+ users`, `\d+ ride_request`,
-- `\d+ chat_messages` in psql) — this was written from the JPA entity
-- mappings, not by introspecting the live database directly.

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS ride_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    pickup_hub   VARCHAR(255),
    destination  VARCHAR(255),
    created_at   TIMESTAMP,
    group_id     VARCHAR(255),
    status       VARCHAR(255),
    user_id      BIGINT,
    CONSTRAINT fk_ride_request_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     VARCHAR(255) NOT NULL,
    sender_name  VARCHAR(255) NOT NULL,
    message      TEXT NOT NULL,
    timestamp    TIMESTAMP NOT NULL
);
